# Generated by Django 6.0.4 on 2026-04-21 02:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'API Fetch')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Fire', 'Fire'), ('Water', 'Water'), ('Grass', 'Grass'), ('Electric', 'Electric'), ('Normal', 'Normal')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.datarun')),
                ('primary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pokemontype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'primary_type')},
            },
        ),
    ]
