# Generated by Django 6.0.4 on 2026-04-22 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_city_id_alter_datarun_id_alter_pokemon_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='secondary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_pokemon', to='myapp.pokemontype'),
        ),
    ]
