# Generated by Django 5.2.13 on 2026-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pokemon_secondary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemontype',
            name='name',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Water', 'Water'), ('Grass', 'Grass'), ('Electric', 'Electric'), ('Normal', 'Normal'), ('Ice', 'Ice')], max_length=20, unique=True),
        ),
    ]
